spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: system
          uri: http://127.0.0.1:9001
          predicates:
            - Path=/system/**

server:
  port: 9000
eureka:
  instance:
    instance-id: gateway${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

