spring:
  application:
    name: system

server:
  port: 9001
  servlet:
    context-path: /system

eureka:
  instance:
    instance-id: system${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
